### ISSUE TITLE
Switching layouts stops on German Neo2 if it's not the first layout

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#210] opened 2021-02-02 22:51 UTC
So if we have German, Neo 2 variant as the first layout - it switches to the next just fine, and then by the loop:
Neo 2 <- -> US

If we just change the order, switching stops on Neo:
US  (X) <- -> (OK) Neo 2
or
US -> (OK) Neo 2 -> (X) UK

Tested with CapsLock and RCtl+RShift as group switchers, on both Gnome and Plasma, Wayland and X11 sessions.
Downstream report: https://bugs.kde.org/show_bug.cgi?id=432436

**Comment by bluetech** [comment] 2021-02-09 13:52
I am able to reproduce this with:

```
sudo ./build/xkbcli-interactive-evdev --layout 'us,de' --variant ,neo --option grp:rctrl_rshift_toggle
```

RCtrl + RShift toggles to Neo, but another time doesn't. The problem is some conflict on how the modifiers are used. Particularly, commenting out this line in the `de(neo)` map makes it work:

https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/aeed643124d761c85c55bb2668162afd7bca55b9/symbols/de#L558

```
    include "shift(both_capslock)"
```

Note:

```
$ xkbcli list | grep shift:both_capslock::
  - shift:both_capslock::Both Shift together enable Caps Lock
```

I don't have time to check it in any more depth ATM, but I suggest reporting this to xkeyboard-config because it's *probably* not something on the xkbcommon (keymap compiling/interpretation) side.

**Comment by bam80** [comment] 2021-02-09 23:51
Thank you for your investigation Ran!
I've crossposted it here: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/252

**Comment by bluetech** [comment] 2021-02-27 20:16
I'll close this now, but feel free to reopen if it's something xkbcommon can help with.

**Closed by bluetech** 2021-02-27 20:16 UTC
