### ISSUE TITLE
Build error: 'ascii' codec can't encode character 

### ISSUE THREAD

**Issue by Knitschi** [xkbcommon/libxkbcommon#195] opened 2020-10-18 08:32 UTC
Hi guys

I am not sure if this is the correct place to post my problem, because it happens so deep down in my toolchain that I have no clue what is going on.

I am using the conan package manager to build the Qt 5.15.0 package. Conan will first compile the dependencies of Qt. One of those seems to be the xkbcommon package which I assume is the one that is hosted in this repository. When conan compiles xkbcommon it yields the following error:

```
Build targets in project: 33
WARNING: Project specifies a minimum meson_version '>= 0.41.0' but uses features which were added in newer versions:
 * 0.50.0: {'install arg in configure_file'}
Found ninja-1.10.0 at /home/jenkins/.conan/data/ninja/1.10.0/_/_/package/8e6304b6ad31b530c81dcec12707f6abe98f2a1f/bin/ninja
ninja: Entering directory `/home/jenkins/.conan/data/xkbcommon/0.10.0/_/_/build/5828f2b7a79f1667cc367c9e92bd6a0b26148ccc/build_subfolder'
[1/139] Generating source from 'src/xkbcomp/parser.y'.
'ascii' codec can't encode character '\u2018' in position 81: ordinal not in range(128)
```

So a quick search tells me that this seems to by a frequent problem in python. So I am not sure if it is even caused by your project or by meson or by ninja or ...

Maybe you have encountered the problem an can help me to find the guys who are responsible.

Thanks

**Comment by bluetech** [comment] 2020-10-19 07:15
It looks like it's coming from meson but I'm not sure.

Which meson version are you using?

Is this all of the output you get? Can you run meson with `--verbose`? Can you run it with the `MESON_FORCE_BACKTRACE=1` envvar?

What locale are you using? (You can use the `locale` command to print that)

Does it still happen on xkbcommon master?

**Comment by Knitschi** [comment] 2020-10-19 11:58
I am not directly building xkbcommon myself. I use the conan package manager to build qt, which then triggers building xkbcommon. This makes it harder for me to reproduce the problem with a non-conan based local build.
It will take me some days befor I can answer you questions.

**Comment by Knitschi** [comment] 2020-10-24 12:37
Meson Version: 0.54.2
locale command output: 

```
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

At this point i will not try to drill down into the problem. In the meantime I found out that the problem does not occurr when I build the Qt package on the ```ubuntu-20.04``` machine that is one of the default runner machines that are provided by github for running github actions. Instead of solving the problem I will try to change the configuration of my own CI-client to match the configuration of the github machine and hope that my problems will disappear then.

**Comment by bluetech** [comment] 2020-10-25 08:27
So the problem is likely the POSIX locale. It is a very restrictive locale, only allowing ASCII, and somewhere there is a non-ASCII file. I guess either meson or us don't handle it.

The best solution is to use a better locale, like `en_US.UTF-8` or such.

Since [Python 3.7](https://www.python.org/dev/peps/pep-0538/), Python itself interprets the POSIX locale as UTF-8. Am I correct you using a version older than that? If so, another solution is to update your Python.

**Comment by Knitschi** [comment] 2020-10-28 15:22
Thank you for your hints. I will try to set a different locale. You are correct. I am using python 3.6 because later versions currently have a bug in the unittest module that causes problems in my project.

**Comment by bluetech** [comment] 2020-11-25 07:39
I'll close this then as I don't really want to handle the ASCII locale case...

**Closed by bluetech** 2020-11-25 07:39 UTC
