### ISSUE TITLE
Wrong codepoint for almost equal to

### ISSUE THREAD

**Issue by svenssonaxel** [xkbcommon/libxkbcommon#110] opened 2019-09-27 15:19 UTC
In `xkbcommon/xkbcommon-keysyms.h`, the line:
```
#define XKB_KEY_approxeq                   0x1002248  /* U+2245 ALMOST EQUAL TO */
```

should probably be changed to
```
#define XKB_KEY_approxeq                   0x1002248  /* U+2248 ALMOST EQUAL TO */
```

**Comment by bluetech** [comment] 2019-09-28 10:45
The file is autogenerated. Here is the source: https://gitlab.freedesktop.org/xorg/proto/xorgproto/blob/e0d4e02710e6d66408ecbbd2fee64ae4c6748739/include/X11/keysymdef.h#L2136

Once it is fixed there, we can regenerate the file here.

**Comment by fooishbar** [comment] 2019-09-30 22:20
Dupe of #82.

**Closed by fooishbar** 2019-09-30 22:20 UTC

**Comment by svenssonaxel** [comment] 2021-03-28 11:24
Fixed in source by deprecating `XK_approxeq` and `XK_notapproxeq`.
