### ISSUE TITLE
1.0.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [xkbcommon/libxkbcommon#187] opened 2020-09-07 02:19 UTC
```
+ cd libxkbcommon-1.0.0
+ /usr/bin/meson test -C x86_64-redhat-linux-gnu --num-processes 48 --print-errorlogs
ninja: Entering directory `/home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0/x86_64-redhat-linux-gnu'
ninja: no work to do.
 1/20 libxkbcommon / keysym                           OK             0.07s
 2/20 libxkbcommon / keymap                           OK             0.06s
 3/20 libxkbcommon / filecomp                         OK             0.07s
 4/20 libxkbcommon / context                          OK             0.02s
 5/20 libxkbcommon / rules-file                       OK             0.09s
 6/20 libxkbcommon / rules-file-includes              OK             0.06s
 7/20 libxkbcommon / stringcomp                       OK             0.07s
 8/20 libxkbcommon / buffercomp                       OK             0.06s
 9/20 libxkbcommon / log                              OK             0.03s
10/20 libxkbcommon / atom                             OK             0.15s
11/20 libxkbcommon / utf8                             OK             0.04s
12/20 libxkbcommon / state                            OK             0.07s
13/20 libxkbcommon / keyseq                           OK             0.08s
14/20 libxkbcommon / rulescomp                        OK             0.12s
15/20 libxkbcommon / compose                          OK             0.08s
16/20 libxkbcommon / utils                            OK             0.05s
17/20 libxkbcommon:python-tests / symbols-leak-test   OK             0.11s
18/20 libxkbcommon / x11                              SKIP           0.03s
19/20 libxkbcommon / registry                         OK             0.03s
20/20 libxkbcommon:python-tests / tool-option-parsing FAIL           3.77s (exit status 1)

Ok:                 18
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            1
Timeout:            0


The output from the failed tests:

20/20 libxkbcommon:python-tests / tool-option-parsing FAIL           3.77s (exit status 1)

--- command ---
02:17:10 XKB_LOG_VERBOSITY='10' XKB_LOG_LEVEL='debug' top_srcdir='/home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0' top_builddir='/home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0/x86_64-redhat-linux-gnu' /home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0/test/tool-option-parsing.py
--- stdout ---
============================= test session starts ==============================
platform linux -- Python 3.8.3, pytest-4.6.9, py-1.8.0, pluggy-0.13.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0/x86_64-redhat-linux-gnu/.hypothesis/examples')
rootdir: /home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0
plugins: forked-1.1.1, mock-1.10.4, expect-1.1.0, hypothesis-4.23.8, xdist-1.31.0, httpbin-0.3.0, cov-2.8.1, timeout-1.3.4, rerunfailures-8.0, flaky-3.6.1
collected 113 items

../test/tool-option-parsing.py ..............F.......................... [ 36%]
.........................................sssssssssssssssssssssssssssssss [100%]

=================================== FAILURES ===================================
_____________________________ test_xkbcli_version ______________________________

xkbcli = <tool-option-parsing.XkbcliTool object at 0x7fd32c6bbd00>

    def test_xkbcli_version(xkbcli):
        stdout, stderr = xkbcli.run_command_success(['--version'])
>       assert stdout.startswith('0')
E       AssertionError: assert False
E        +  where False = <built-in method startswith of str object at 0x7fd32c6b73b0>('0')
E        +    where <built-in method startswith of str object at 0x7fd32c6b73b0> = '1.0.0\n'.startswith

../test/tool-option-parsing.py:173: AssertionError
----------------------------- Captured stderr call -----------------------------
DEBUG:test:run command: /home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0/x86_64-redhat-linux-gnu/xkbcli --version
------------------------------ Captured log call -------------------------------
DEBUG    test:tool-option-parsing.py:57 run command: /home/tkloczko/rpmbuild/BUILD/libxkbcommon-1.0.0/x86_64-redhat-linux-gnu/xkbcli --version
=============== 1 failed, 81 passed, 31 skipped in 2.11 seconds ================
-------
```

**Comment by whot** [comment] 2020-09-07 02:28
Duplicate of #185

**Closed** 2020-09-07 02:28 UTC

**Comment by kloczek** [comment] 2020-09-11 13:28
Just checked 1.0.1 and everything looks good.

Thank you :)
