### ISSUE TITLE
can't add more than 4 layouts to the keymap

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#311] opened 2022-12-13 13:03 UTC
https://github.com/xkbcommon/libxkbcommon/blob/2530f6444bfad2bf67ee926e57df8987afeebf4a/src/keymap.h#L91-L104
> This limit is artificially enforced

It's not documented anywhere, which is an issue per se I already faced, and also it might be useful to add more layouts for example as in our KDE KWin's unit tests (I'll provide the link).
@bluetech

**Comment by whot** [comment] 2023-05-02 03:22
Realistically, the  main limitation here is XKB. The XKB protocol (the X11 bit) has the limit of 4 groups hardcoded, so if we want to stay compatible to that (and we do, for the forseeable future) extending this is not an option.

A quick peek of the protocol indicates only `XkbGetMap` has that *actually* as a sized limit (`ktIndex` is limited to 4 groups), afaict everything else could make use of at least 256 or (as in that comment) 32 where used as mask. But `XkbNumKbdGroups` has been `#defined` to 4 for decades now and I'm sure there is plenty of code out there that hardcodes it. the protocol also defines `KB_GROUPMASK` as 1-4 groups, so extending this will also cause issues.

**Comment by bam80** [comment] 2023-05-02 07:45
Could we make in opt-in maybe? Because right now we already faced with the real issue above due to the limitation, which needs to be solved anyway.

**Comment by wismill** [comment] 2024-07-12 08:00
Duplicate of #37, let’s continue the discussion there as it has more info.

**Closed by wismill** 2024-07-12 08:00 UTC
Labels: X11 legacy: limitations
