### ISSUE TITLE
Drop-in configuration support

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#114] opened 2019-10-19 22:32 UTC
Hi,
is it possible to have all the files with the same name in include paths processed, so we could make small drop-in additions to existing configuration, without changing the lib's program behavior?

Something like systemd units drop-in ".d/" directories would be fine.

**Comment by whot** [comment] 2019-11-15 00:50
fwiw #108 is somewhat related here

**Comment by bluetech** [comment] 2019-12-14 13:03
Where would the drop in directories be located? The system path is read-only, and we don't have an `/etc/xkb`. So that leaves the `$XDG_CONFIG_DIR/xkb/`. But it feels unnatural to me to use drop-in directories there?

One thing we can start with, which might be easier: say we want to augment `symbols/us`, then add `$XDG_CONFIG_DIR/xkb/symbols/us` with

```xkb
xkb_symbols "basic" {
    replace key <TLDE> { [ X, Y ] };
    include "us(basic)"
}
```

This currently doesn't work - gets into an endless `include` loop, trying to include itself. But if we can make it do the right thing, it'd be a straightforward way to "drop in" changes without needing to change the RMLVO (Rules, Model, Layout, Variant, Options configuration).

**Comment by mar04** [comment] 2020-01-27 01:33
I have exactly this use case. I want to have an easy way of typing German umlauts on Polish keyboard, so I added a variant to xkb/symbols/pl and xkb/rules/evdev.{lst,xml}. It works great, except now I have to merge those files every time the xkb package is updated.

**Comment by whot** [comment] 2020-07-06 05:20
This is now possible with #108 and #146 , at least from the libxkbcommon perspective.

**Comment by ossilator** [comment] 2020-07-06 10:01
i would call this a straight duplicate of #40. let's discuss there.

**Closed** 2021-02-27 20:20 UTC
