### ISSUE TITLE
How to read used keysyms/keycodes for each modifier_map

### ISSUE THREAD

**Issue by ldrahnik** [xkbcommon/libxkbcommon#480] opened 2024-04-14 21:38 UTC
I do not know how I can read keysyms or keycodes for each `modifier_map` below. Do I understand well used keysym are substitutable? Modifier `Shift` means can be pressed left or right Shift. I only care about first keysym in case previous statement  is true. I know that func `keymap.get_as_string()` below returns at the end of output what I need but I would like to avoid using `regexp` and have another table translating `LFSH` -> `Shift_L`, `RTSH` -> `Shift_R` for which then I could easily find keycode using func `xkb.keysym_from_name` and iterating over all keycodes inside keymap and comparing keysym for first level but I would prefer something similar to `Xlib` example below and I have not found an equivalent func inside `KeyboardState`:

Output of `keymap.get_as_string()`:
```
...
        modifier_map Shift { <LFSH>, <RTSH> };
        modifier_map Lock { <CAPS> };
        modifier_map Control { <LCTL>, <RCTL> };
        modifier_map Mod1 { <LALT>, <RALT>, <META> };
        modifier_map Mod2 { <NMLK> };
        modifier_map Mod4 { <LWIN>, <RWIN>, <SUPR>, <HYPR> };
        modifier_map Mod5 { <LVL3>, <MDSW> };
```

Using `Xlib` I can do something like:

```
    mods = display.get_modifier_mapping()
    mod_shift = mods[Xlib.X.ShiftMapIndex]
    first_keycode_for_mod_shift = mod_shift[0]
	second_keycode_for_mod_shift = mod_shift[1]
    key = EV_KEY.codes[int(first_keycode_for_mod_shift) - 8]
    # key -> KEY_LEFTSHIFT
    key = EV_KEY.codes[int(second_keycode_for_mod_shift) - 8]
    # key -> KEY_RIGHTSHIFT
...
```

Could help me anyone with a better understanding, please.

**Comment by wismill** [comment] 2024-04-15 05:32
Duplicate of #91. TL;DR: There is no such API. 

Could you explain you use case?

**Comment by ldrahnik** [comment] 2024-04-16 18:59
I develop a driver for Asus laptops with hardware support for NumberPad. NumberPad is an illuminated numeric keypad integrated to the touchpad which appears when is done tap on the top right corner of the touchpad. In [this](https://github.com/asus-linux-drivers/asus-numberpad-driver/pull/175) branch of driver I try to add support for rebinding modifiers as well as other keys for wayland. Xlib I will solve with code as I posted in issue because atm does not exist bindings for this lib for python supporting x11. Atm I have in the mentioned WIP branch this table which I would like to using dynamic findings, Shift might be something else then `Shift_L` or `Shift_R` for example:

```
    mods_to_evdev_key_names = {
        'Control': 'Control_L',
        'Shift': 'Shift_L',
        'Lock': 'Caps_Lock',
        'Mod1': '', # TODO:
        'Mod2': '', # TODO:
        'Mod3': '', # TODO:
        'Mod4': '', # TODO:
        'Mod5': '', # TODO:
        'NumLock': 'Num_Lock',
        'Alt': 'Alt_L',
        'LevelThree': '', # TODO:
        'LAlt': 'Alt_L',
        'RAlt': 'Alt_R',
        'RControl': 'Control_R',
        'LControl': 'Control_L',
        'ScrollLock': 'Scroll_Lock',
        'LevelFive': '', # TODO:
        'AltGr': 'Alt_R',
        'Meta': 'Meta_L',
        'Super': 'Meta_L',
        'Hyper': 'Hyper_L'
    }
```

**Comment by ldrahnik** [comment] 2024-04-22 10:52
@wismill What do you think? Should I try to implement the workaround solution mentioned in #91? About the proposed modification mentioned in #91 something like that does what I need. By index in keymap find all keycodes and return them thought pointer and as return value return the length of the keycodes array.

**Comment by ldrahnik** [comment] 2024-04-24 23:03
I wrote the code below so I think I am able get keycode for `Shift` modifier at least, others I have not tested yet. How I can get `Shift_L`|`Shift_R` instead of keycode?

```
     mod_name = 'Shift'

     keymap = keyboard_state.get_keymap()
     num_mods = keymap.num_mods()
 
     for keycode in keymap:
     	key_state = keyboard_state.update_key(keycode, xkb.KeyDirection.XKB_KEY_DOWN)
 
        num_layouts = keymap.num_layouts_for_key(keycode)
        for layout in range(0, num_layouts):
 
            layout_is_active = keyboard_state.layout_index_is_active(layout, xkb.StateComponent.XKB_STATE_LAYOUT_EFFECTIVE)
 
            if layout_is_active:
                for mod_index in range(0, num_mods):
 
                    is_key_mod = key_state | xkb.StateComponent.XKB_STATE_MODS_DEPRESSED
                    if is_key_mod:
 
                                is_mod_active = keyboard_state.mod_index_is_active(mod_index, xkb.StateComponent.XKB_STATE_MODS_DEPRESSED)
                                if is_mod_active:
                                    if keymap.mod_get_name(mod_index) == mod_name:
                                        print(mod_name)
                                        print(keycode)
                                        return keycode
 
            keyboard_state.update_key(keycode, xkb.KeyDirection.XKB_KEY_UP)
```

**Comment by ldrahnik** [comment] 2024-04-26 14:08
Thank you. With 2 mentioned changes I get for `Shift`:

output
```
Shift
50
Shift_L
Shift
62
Shift_R
```

**Closed** 2024-04-26 14:55 UTC
