### ISSUE TITLE
Segmentation fault when mixing with Blender

### ISSUE THREAD

**Issue by LuizVSilva** [xkbcommon/libxkbcommon#371] opened 2023-08-07 13:07 UTC
Hi,
I am posting this issue here, origianted in Blender, because I think is related to libxkbcommon.

Some erro background:
- System: Ubuntu  22.04
- Blender: 3.6.1
- OpenCV used in blender: 4.8 (last release - others tested as well)
- libxkbcommon used in OpenCV: 1.4.1 (try with 1.5.0 but no expertise to compile with meson, so I gave up)

Original post in blender foruns (please, take a look)
- https://projects.blender.org/blender/blender/issues/110842#issuecomment-993417

Error (described in blender issues post)
```
#0 0x00007fff63405263 in find_atom_pointer ()
   from /me/blender/blender-3.6.1-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libxkbcommon-x11-c65ed502.so.0.0.0
```

I am not sure who exactly is the cause, but if not Blender it self, maybe sobre missing behavior using libxkbcommon from OpenCV.

Any help would be great!

**Comment by bluetech** [comment] 2023-08-10 20:27
Hi,

If you run `xkbcli interactive-x11` in your shell, does it crash the same?

Otherwise, if you can get a debug version xkbcommon in there so that we have a line number for the crash, that would be most helpful.

Otherwise, please run `xkbcomp $DISPLAY keymap.xkb` and attach the keymap.xkb file.

**Comment by LuizVSilva** [comment] 2023-08-11 11:55
**Command:**
`xkbcli interactive-x11`
**Result**:
Small white frame opened. Ended with 'CTRL + C'

**Command:**
xkbcomp $DISPLAY keymap.xkb
**Result**:
File attached (renamed to TXT to be uploaded)
[keymap.txt](https://github.com/xkbcommon/libxkbcommon/files/12321114/keymap.txt)

About debugging xkbcommon, not sure how to do it. I will try.

**Comment by wismill** [comment] 2023-09-12 14:36
> Command:
xkbcli interactive-x11
Result:
Small white frame opened. Ended with 'CTRL + C'

You should focus this small window then try to type various typical keys you use in your application. Then close this windows and copy the output of the command in the console, then report it here.

**Comment by LuizVSilva** [comment] 2023-09-19 14:09
I've already done it before with the most exotic combinations used in Blender. No crash. I'll try it again to post results.

**Comment by wismill** [comment] 2023-09-28 12:21
The output looks good to me.

> ESC = ends xkbcli

this is intended

> CTRL + ALT + D = change focus from everything

no idea what you mean.

Anyway, as I expect there is no crash while using the interactive tool, so I think the issue is with the incorrect use of the API of xkbcommon, or with the API of X11. I have no clue about what is happening.

**Comment by LuizVSilva** [comment] 2023-09-28 12:29
Thx anyway. 
I'll investigate further and post any progress.

**Comment by wismill** [comment] 2023-09-28 12:36
I am going to close this issue, as it does not seem related to xkbcommon itself. As the ticket you posted on blender website suggested, please check if the issue is with opencv.

Feel free to re-open if there is evidence that the issue is with xkbcommon, or if the xkbcommon API need clarification.

**Closed** 2023-09-28 12:36 UTC
Labels: needs info
