### ISSUE TITLE
1.2.0 regression: Keymap for X11 device fails to compile

### ISSUE THREAD

**Issue by heftig** [xkbcommon/libxkbcommon#229] opened 2021-04-06 21:34 UTC
Since 1.2.0, the keymap for an X11 device fails to compile in at least one situation. This was first seen with Qt 5's XCB backend, but also affects `xkbcli`.

Environment: Arch Linux, GNOME 40, Wayland (XWayland)

Steps to reproduce:
1. Open `gnome-tweaks` and enable *Keyboard & Mouse* → *Additional Layout Options* → *Compatibility options* →
   ***Numeric keypad always enters digits (as in macOS)***.
2. Start `xkbcli interactive-x11`

```
> xkbcli interactive-x11
Couldn't initialize core keyboard device
```

Bisected to 40c00b472144d1684d2fb97cafef39ef59f21b28
Downstream bug: https://bugs.archlinux.org/task/70293

**Comment by bluetech** [comment] 2021-04-07 07:12
Can confirm, enabling that options makes it fail. Pretty strange. Will look at it soon. Also cc @psychon in case they beat me to it.

**Comment by bluetech** [comment] 2021-04-07 07:54
So I had a quick look already and the issue is straightforward, I sent pr #230 to fix it. I will try to merge and release 1.2.1 tonight.

Writing a unit test for this is a bit complicated, but I am pretty confident in the fix, so I won't hold the release for it.

**Comment by bluetech** [comment] 2021-04-07 07:58
I forgot to say: thanks @heftig and the other people on the Arch Linux bug for reporting and bisecting, it's really helpful.

**Comment by heftig** [comment] 2021-04-07 08:44
Thanks; I can confirm that #230 fixes the bug for me.

**Comment by rad83** [comment] 2021-04-07 08:55
Another Arch user from downstream bug here.
I can see that this bug is probably already fixed (thank you for such quick fix!), however my 'steps to reproduce' are bit different (at least in my point of view, maybe it is connected somehow). I use KDE/Plasma, therefore systemsettings5.

Steps to reproduce:
SystemSettings -> Input Devices -> Keyboard -> Hardware -> Keyboard model:
Select "Apple | MacBook/MacBook Pro (intl.)". That is enough, other Apple models will probably also work.
If (for instance) "Generic | Generic 101-key PC" model is selected, the input works just fine. It does not matter if any "keyboard options" from "Advanced" tab is selected (so in my case, enabling/disabling  "Numeric keypad always enters digits" compatibility options has no effect).

However, I did not test the fix, I will try it as soon as it will be released. So let's assume the fix works, I just wanted to point out it might not be conected directly to that single Compatibility option.

**Comment by heftig** [comment] 2021-04-07 09:52
Arch's 1.2.0-2 has the fix, if you want to test it earlier.

**Comment by rad83** [comment] 2021-04-07 10:10
Great, so I can confirm that this fix works for me as well.
Thanks everybody for such excelent work!

**Closed** 2021-04-07 16:21 UTC

**Comment by psychon** [comment] 2021-04-08 16:21
>  Also cc @psychon in case they beat me to it.

Thanks for the cc and sorry for the bug. Glad you were able to fix it so quickly.

> I forgot to say: thanks @heftig and the other people on the Arch Linux bug for reporting and bisecting, it's really helpful.

Yup, this is really a great bug report!
