### ISSUE TITLE
error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment whose length is between 1 and 16 characters

### ISSUE THREAD

**Issue by ryandesign** [xkbcommon/libxkbcommon#386] opened 2023-10-10 01:10 UTC
Hi, I'm the maintainer of [libxkbcommon in MacPorts](https://ports.macports.org/port/libxkbcommon). In trying to update to version 1.6.0, I found that the x11 parts don't build for me on macOS 12.6.8 on x86_64:

```
FAILED: test-x11.p/test_x11.c.o 
ccache /usr/bin/clang -Itest-x11.p -I. -I../libxkbcommon-1.6.0 -I../libxkbcommon-1.6.0/src -I../libxkbcommon-1.6.0/include -I/opt/local/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wshadow -Wdate-time -Wwrite-strings -Wno-documentation-deprecated-sync -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MQ test-x11.p/test_x11.c.o -MF test-x11.p/test_x11.c.o.d -o test-x11.p/test_x11.c.o -c ../libxkbcommon-1.6.0/test/x11.c
../libxkbcommon-1.6.0/test/x11.c:30:1: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment whose length is between 1 and 16 characters
X11_TEST(test_basic)
^
../libxkbcommon-1.6.0/test/xvfb-wrapper.h:35:24: note: expanded from macro 'X11_TEST'
__attribute__((section("test_functions_section"))) = { \
                       ^
1 error generated.
[182/205] ccache /usr/bin/clang -Itest-x11comp.p -I. -I../libxkbcommon-1.6.0 -I../libxkbcommon-1.6.0/src -I../libxkbcommon-1.6.0/include -I/opt/local/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wshadow -Wdate-time -Wwrite-strings -Wno-documentation-deprecated-sync -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MQ test-x11comp.p/test_x11comp.c.o -MF test-x11comp.p/test_x11comp.c.o.d -o test-x11comp.p/test_x11comp.c.o -c ../libxkbcommon-1.6.0/test/x11comp.c
FAILED: test-x11comp.p/test_x11comp.c.o 
ccache /usr/bin/clang -Itest-x11comp.p -I. -I../libxkbcommon-1.6.0 -I../libxkbcommon-1.6.0/src -I../libxkbcommon-1.6.0/include -I/opt/local/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wshadow -Wdate-time -Wwrite-strings -Wno-documentation-deprecated-sync -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MQ test-x11comp.p/test_x11comp.c.o -MF test-x11comp.p/test_x11comp.c.o.d -o test-x11comp.p/test_x11comp.c.o -c ../libxkbcommon-1.6.0/test/x11comp.c
../libxkbcommon-1.6.0/test/x11comp.c:38:1: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment whose length is between 1 and 16 characters
X11_TEST(test_basic)
^
../libxkbcommon-1.6.0/test/xvfb-wrapper.h:35:24: note: expanded from macro 'X11_TEST'
__attribute__((section("test_functions_section"))) = { \
                       ^
1 error generated.
```

The non-x11 parts of 1.6.0 build fine.

All parts of 1.5.0 built fine so this is a regression.

**Comment by whot** [comment] 2023-10-10 02:35
> mach-o section specifier requires a segment whose length is between 1 and 16 characters

Does it work after a `sed -i 's/test_functions_sections/test_func_sec/' **/*`? If so, that's an easy enough fix.

**Comment by ryandesign** [comment] 2023-10-15 10:06
After applying `s/test_functions_section/test_func_sec/g`, the next failure is:

```
FAILED: test-x11.p/test_x11.c.o 
ccache /usr/bin/clang -Itest-x11.p -I. -I../libxkbcommon-1.6.0 -I../libxkbcommon-1.6.0/src -I../libxkbcommon-1.6.0/include -I/opt/local/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wshadow -Wdate-time -Wwrite-strings -Wno-documentation-deprecated-sync -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MQ test-x11.p/test_x11.c.o -MF test-x11.p/test_x11.c.o.d -o test-x11.p/test_x11.c.o -c ../libxkbcommon-1.6.0/test/x11.c
../libxkbcommon-1.6.0/test/x11.c:30:1: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
X11_TEST(test_basic)
^
../libxkbcommon-1.6.0/test/xvfb-wrapper.h:35:24: note: expanded from macro 'X11_TEST'
__attribute__((section("test_func_sec"))) = { \
                       ^
1 error generated.
[193/205] ccache /usr/bin/clang -Itest-x11comp.p -I. -I../libxkbcommon-1.6.0 -I../libxkbcommon-1.6.0/src -I../libxkbcommon-1.6.0/include -I/opt/local/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wshadow -Wdate-time -Wwrite-strings -Wno-documentation-deprecated-sync -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MQ test-x11comp.p/test_x11comp.c.o -MF test-x11comp.p/test_x11comp.c.o.d -o test-x11comp.p/test_x11comp.c.o -c ../libxkbcommon-1.6.0/test/x11comp.c
FAILED: test-x11comp.p/test_x11comp.c.o 
ccache /usr/bin/clang -Itest-x11comp.p -I. -I../libxkbcommon-1.6.0 -I../libxkbcommon-1.6.0/src -I../libxkbcommon-1.6.0/include -I/opt/local/include -fcolor-diagnostics -Wall -Winvalid-pch -Wextra -std=c11 -O0 -g -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wshadow -Wdate-time -Wwrite-strings -Wno-documentation-deprecated-sync -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -arch x86_64 -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -MD -MQ test-x11comp.p/test_x11comp.c.o -MF test-x11comp.p/test_x11comp.c.o.d -o test-x11comp.p/test_x11comp.c.o -c ../libxkbcommon-1.6.0/test/x11comp.c
../libxkbcommon-1.6.0/test/x11comp.c:38:1: error: argument to 'section' attribute is not valid for this target: mach-o section specifier requires a segment and section separated by a comma
X11_TEST(test_basic)
^
../libxkbcommon-1.6.0/test/xvfb-wrapper.h:35:24: note: expanded from macro 'X11_TEST'
__attribute__((section("test_func_sec"))) = { \
                       ^
1 error generated.
```

**Comment by whot** [comment] 2023-10-16 21:54
after a bit of googling around [[1]](https://stackoverflow.com/questions/47896174/how-can-i-sections-out-of-text-and-into-a-new-segment-for-a-mach-o-binary), a possible solution is
```
__attribute__((section("__TEXT,test_func_sec")))
```
which may get past the compilation (not on linux though, so an ifdef is needed here). If it does the lookup in `test/xvfb-wrapper.c` is likely to fail, would be nice if you could figure out what the names are. This is a bit difficult to debug remotely.

**Comment by wismill** [comment] 2023-11-03 03:36
@ryandesign kind reminder

**Comment by wismill** [comment] 2023-11-14 15:48
@ryandesign could you give a try to Peter's suggestions?

**Comment by wismill** [comment] 2024-02-23 18:13
Closing as stale. Feel free to re-open if you have some news.

**Comment by ryandesign** [comment] 2024-02-25 20:11
I was not planning on working on this. I don't know your code.

If you don't plan to fix this, then I guess your software no longer supports macOS and I should consider removing it from MacPorts.

**Comment by wismill** [comment] 2024-02-26 06:19
> If you don't plan to fix this, then I guess your software no longer supports macOS and I should consider removing it from MacPorts.

@ryandesign I think it's overacted to remove software whose last buildable version (here 1.5) on your platform is barely _a year old_. It is _not_ an obsolete version: e.g. lots of Linux distribution currently ship this version (or maybe older ones).

> I was not planning on working on this. I don't know your code.

We do not ask you to know the code, but to test a _single line_ fix because **we do not reproduce the failure on our CI**. Peter gave instructions above and you are welcome to ask for further help.

I closed this issue simply because we had no feedback for a few months but invited you to re-open it whenever you find time to test the proposed fix.

**Comment by chenrui333** [comment] 2024-03-10 21:25
@wismill hi folks, I tried the suggested patch today, here is the exact one, https://gist.github.com/chenrui333/9d50b548115ead84522b5205edb7fec9

And I ran into some issue that I could not figured out.

```
[184/202] clang  -o test-x11 test-x11.p/test_x11.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/homebrew/Cellar/libxcb/1.16.1/lib libxkbcommon-x11-internal.a libxkbcommon-test-internal.a /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb.dylib /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb-xkb.dylib
FAILED: test-x11
clang  -o test-x11 test-x11.p/test_x11.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/homebrew/Cellar/libxcb/1.16.1/lib libxkbcommon-x11-internal.a libxkbcommon-test-internal.a /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb.dylib /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb-xkb.dylib
Undefined symbols for architecture arm64:
  "___start_test_func", referenced from:
      _x11_tests_run in libxkbcommon-x11-internal.a[8](test_xvfb-wrapper.c.o)
      _x11_tests_run in libxkbcommon-x11-internal.a[8](test_xvfb-wrapper.c.o)
  "___stop_test_func", referenced from:
      _x11_tests_run in libxkbcommon-x11-internal.a[8](test_xvfb-wrapper.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[185/202] clang  -o test-x11comp test-x11comp.p/test_x11comp.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/homebrew/Cellar/libxcb/1.16.1/lib libxkbcommon-x11-internal.a libxkbcommon-test-internal.a /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb.dylib /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb-xkb.dylib
FAILED: test-x11comp
clang  -o test-x11comp test-x11comp.p/test_x11comp.c.o -Wl,-dead_strip_dylibs -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/homebrew/Cellar/libxcb/1.16.1/lib libxkbcommon-x11-internal.a libxkbcommon-test-internal.a /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb.dylib /opt/homebrew/Cellar/libxcb/1.16.1/lib/libxcb-xkb.dylib
Undefined symbols for architecture arm64:
  "___start_test_func", referenced from:
      _x11_tests_run in libxkbcommon-x11-internal.a[8](test_xvfb-wrapper.c.o)
      _x11_tests_run in libxkbcommon-x11-internal.a[8](test_xvfb-wrapper.c.o)
  "___stop_test_func", referenced from:
      _x11_tests_run in libxkbcommon-x11-internal.a[8](test_xvfb-wrapper.c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any help would be appreciated.

(Also it might be good to setup macos build to prevent this from happening again)

**Comment by wismill** [comment] 2024-03-11 18:16
@chenrui333 Thanks for your feedback! Could you give a try to #468?

> (Also it might be good to setup macos build to prevent this from happening again)

We already have [a CI for macOS](https://github.com/xkbcommon/libxkbcommon/blob/master/.github/workflows/macos.yml) for some time now, and it passes. This is why we ask for help, because we cannot reproduce the issue in the CI.

**Comment by chenrui333** [comment] 2024-03-12 14:03
yeah, I can give that PR a shot. one sec.

**Closed** 2024-03-15 14:57 UTC
Labels: compiler warning, needs info
